### PR TITLE
feat(library): Introduce build of base / ELF Loader w/o embedded initrd

### PR DESCRIPTION
**Pull request by razvand**
This is a classic build of base / ELF Loader that doesn't use embedded initramdisk and that doesn't automount the root filesystem. The root filesystem is to be passed as a boot option via `vfs.fstab` with an initial ramdisk. The full option is would be

```
vfs.fstab=[ "initrd:/:initrd:::" ]
```

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by razvand** [comment]
> All good. Reviewed-by: Stefan Jumarea [stefanjumarea02@gmail.com](mailto:stefanjumarea02@gmail.com) Approved-by: Stefan Jumarea [stefanjumarea02@gmail.com](mailto:stefanjumarea02@gmail.com)

@StefanJum , did some updates. Please retry.

**Review by Mihnea0Firoiu — COMMENTED** [review]
Everything works for me.

**Review by StefanJum — APPROVED** [review]
Works fine.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by razvand** [comment]
> Everything works for me.

@Mihnea0Firoiu , please also add you reviewed-by tag, as shown in the [review process](https://unikraft.org/docs/contributing/review-process#finishing-a-review).

**Review by Mihnea0Firoiu — APPROVED** [review]
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

**Comment by RaduNichita** [comment]
All good also by me.

Reviewed-by: Radu Nichita<radunichita99@gmail.com>

**Pull request merged**
