### PR TITLE
feat(examples): Introduce Python 3 helloworld

### PR DESCRIPTION
**Pull request by razvand**
Introduce Python3 as binary compatibility run printing "Hello, World!". Extract / Install Python using `Dockerfile`. Then run it with the `base` kernel images from `../../kernels/`.

Add typical files for a bincompat app:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to generate the root filesystem from the `Dockerfile` rules
* `README.md`: instructions to set up, build and run the application
* `config.yaml`: configuration file to generate scripts to the application
* `helloworld.py`: Python script to print "Hello, World!"

`config.yaml` is used to generate run scripts using the `../../utils/bincompat/generate.py` script.

The kernels in `../../kernels` are generated by running the `../../utils/bincompat/base-build-all.sh` script while inside the `../../library/base/` directory.

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
I get this when running this using the `kraft` command / scripts:
```
 E  could not determine how to run provided input: no arguments supplied
no arguments supplied
cannot run project build without unikraft
cannot run project without runtime directive
no arguments supplied
no arguments supplied
```

And this when running the `qemu` script:
```
ERR:  [appelfloader] <elf_load.c @  134> python3: ELF executable is not position-independent!
ERR:  [appelfloader] <elf_load.c @  961> python3: Parsing of ELF image failed: Exec format error (-8)
```

**Review by StefanJum — APPROVED** [review]
This works fine (except the `kraft` `too many arguments` issue).

**Review by StefanJum — APPROVED** [review]
All good.
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by Mihnea0Firoiu — APPROVED** [review]
All good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Pull request merged**
