### PR TITLE
feat(examples): Introduce HTTP Node server as example

### PR DESCRIPTION
**Pull request by razvand**
Introduce an HTTP Node server as binary compatibility run. Install Node using `Dockerfile`. Then run it with the `base` kernel images from `../../kernels/`.

Add typical files for a bincompat app:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to generate the root filesystem from the `Dockerfile` rules
* `README.md`: instructions to set up, build and run the application
* `config.yaml`: configuration file to generate scripts to the application
* `http_server.js`: HTTP server implementation in Node

`config.yaml` is used to generate run scripts using the `../../utils/bincompat/generate.py` script.

The kernels in `../../kernels` are generated by running the `../../utils/bincompat/base-build-all.sh` script while inside the `../../library/base/` directory.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good.

**Review by RaduNichita — APPROVED** [review]
All good from my side.

Thanks @razvand

**Review by StefanJum — CHANGES_REQUESTED** [review]
This fails on `make initrd` with:
```
#0 7.358 E: Unable to locate package nodejs
------
Dockerfile:3
--------------------
   2 |     
   3 | >>> RUN set -xe ; \
   4 | >>>     apt -yqq update ; \
   5 | >>>     apt -yqq install nodejs \
   6 | >>>     ;
   7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c set -xe ;     apt -yqq update ;     apt -yqq install nodejs     ;" did not complete successfully: exit code: 100
make: *** [../../utils/bincompat/docker.Makefile:6: build] Error 1
```

**Review by Mihnea0Firoiu — COMMENTED** [review]
For me everything works well, I have no problem with ```make initrd```.

**Pull request closed without merging**
