### PR TITLE
feat(examples): Introduce Node Prisma as example

### PR DESCRIPTION
**Pull request by razvand**
Introduce a Node Prisma example as binary compatibility run. Install Node and Prism using `Dockerfile`. Then run it with the `base` kernel images from `../../kernels/`.

Add typical files for a bincompat app:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to generate the root filesystem from the `Dockerfile` rules
* `README.md`: instructions to set up, build and run the application
* `config.yaml`: configuration file to generate scripts to the application

`config.yaml` is used to generate run scripts using the `../../utils/bincompat/generate.py` script.

The kernels in `../../kernels` are generated by running the `../../utils/bincompat/base-build-all.sh` script while inside the `../../library/base/` directory.

### CODE REVIEW

**Review by StefanJum — CHANGES_REQUESTED** [review]
This fails with a `protocol not supported` error. Add it to the README.

**Review by StefanJum — CHANGES_REQUESTED** [review]
This looks like it waits for connections on port 3000, not 8080.
Also, the response is
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```
is this a known issue?

**Comment by Mihnea0Firoiu** [comment]
> This looks like it waits for connections on port 3000, not 8080. Also, the response is
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
> <meta charset="utf-8">
> <title>Error</title>
> </head>
> <body>
> <pre>Cannot GET /</pre>
> </body>
> </html>
> ```
> 
> is this a known issue?

I noticed the same issues.

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Pull request merged**
