### PR TITLE
    feat(examples): Introduce HTTP C server as example

### PR DESCRIPTION
**Pull request by razvand**
Introduce an HTTP C server as binary compatibility run. Build server as a PIE application using `Dockerfile`. Then run it with the `base` kernel images from `../../kernels/`.

Add typical files for a bincompat app:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to generate the root filesystem from the `Dockerfile` rules
* `README.md`: instructions to set up, build and run the application
* `config.yaml`: configuration file to generate scripts to the application
* `http_server.c`: the C HTTP server
    
`config.yaml` is used to generate run scripts using the `../../utils/bincompat/generate.py` script.

The kernels in `../../kernels` are generated by running the `../../utils/bincompat/base-build-all.sh` script while inside the `../../library/base/` directory.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good.

**Comment by RaduNichita** [comment]
All good also from my side.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by Mihnea0Firoiu — APPROVED** [review]
All good.
Reviewed-by: Mihnea Firoiu  <mihneafiroiu0@gmail.com>

**Review by Mihnea0Firoiu — COMMENTED** [review]
`run-qemu-x86_64.sh` works as expected.
`kraft run -M 128M -p 8080:8080` fails with the output:
```
W  unknown or incompatible arch=
E  could not find runtime: too many options
```

`kraft-run-qemu.sh` fails as well with the output: 
```
 E  machine(s) not found
 E  machine(s) not found
virbr0
 E  could not find runtime: too many options
```

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by Mihnea0Firoiu — APPROVED** [review]
All good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

**Pull request closed without merging**
